### ISSUE TITLE
Enable selection of whether to post an item to ActivityPub

### ISSUE THREAD

**Issue by nedjo** [swentel/activitypub#9]
Not all posts may be suitable for sharing. Should be an option per item (e.g., per-node).

Related: #1 

## Tasks

- [ ] Provide a field storage, `field_activitypub_node`, of type `boolean`. Set `locked` and `persist_with_no_fields` to true.
- [ ] Programmatically create a field using this storage on the all bundles of the `node` entity.
    * On module install.
    * In an event listener on field config create.
- [ ] In `hook_form_BASE_FORM_ID_alter()` for node base form, wrap our field in "Fediverse" vertical tab
- Make ActivityPub functionality conditional on field value
- On toggle of field value
    - [ ] Present confirmation page warning of data changes
    - [ ] Delete existing ActivityPub data for the node

... same for other supported entity types, e.g., `media`.

**Comment by swentel** [comment]
I guess I have the same remarks here as I added in #8  - if you opt in the fediverse, and when an administrator has configured the mapping of a content type to an AP type in #7, everything just 'happens'. 

We do need something in storage somewhere to know that the AP part when posting (or doing another action) has been done. But I'm not a 100% sure this should be in a field on the content type. In IndieWeb, when a webmention is send (and when the node is published), this also stored, but in a dedicated entity type. This could be related with #10 a bit then.

**Comment by nedjo** [comment]
> everything just 'happens'.

Yeah, maybe I'm overthinking this. I'm thinking of a use case where an organization doesn't want _everything_ posted to its site. But in any case, this is better modelled per #11. Closing this one.
